### ISSUE TITLE
Error: Storage_account feature flag in Azure provider configuration to enable data plane operations

### ISSUE THREAD

**Issue by thomasthepr0** [Azure/ALZ-PowerShell-Module#315]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

terraform

### Bootstrap Module Version (Optional)

v4.3.1

### Starter Module? (Required)

terraform - platform_landing_zone

### Starter Module Version (Optional)

v5.2.0

### Debug Output/Panic Output (Optional)

```shell

```

### Expected Behaviour (Required)

Should not give any error while running the Deploy-Accelerator command.

### Actual Behaviour (Required)

Hi,

I managed to deploy the ALZ with Terraform. However, the next time I ran the Deploy-Accelerator command, it failed. It prompted me to upgrade the bootstrap version, and I encountered an error after upgrading.

![Image](https://github.com/user-attachments/assets/537b4d60-96de-48bf-a84d-7169739f7799)

Version 4.2.4:  ALZ

**Comment by jaredfholgate** [comment]
This was hopefully resolved with this PR: https://github.com/Azure/accelerator-bootstrap-modules/pull/77

**Comment by thomasthepr0** [comment]
Hi,

I upgraded the version of Bootstrap to v4.3.3 and Starter to v5.2.1, but I’m still encountering the same error.

**Comment by jaredfholgate** [comment]
> Hi,
> 
> I upgraded the version of Bootstrap to v4.3.3 and Starter to v5.2.1, but I’m still encountering the same error. 

Unfortunately the provider implementation is not great. I think you can fix it by editing the state file and setting `queue_properties` and `static_website` to `null`.

**Comment by jaredfholgate** [comment]
> > Hi,
> > 
> > I upgraded the version of Bootstrap to v4.3.3 and Starter to v5.2.1, but I’m still encountering the same error. 
> 
> Unfortunately the provider implementation is not great. I think you can fix it by editing the state file and setting `queue_properties` and `static_website` to `null`.

To be clear, I am referring to the terraform.tfstate file under the bootstrap folder structure. Sorry you have to do this, there is no way to resolve it with Terraform for your particular use case.

The reason for turning off data plane access in the first place was a resolve another issue with authentication.

We'll eventually move to AzAPI and no longer have to deal with this.

**Comment by thomasthepr0** [comment]
If I destroy and redeploy the entire environment, will I face the same error, or is it already fixed in a newer version?

**Comment by thomasthepr0** [comment]
Hi,

I edited the bootstrap v4.3.3 terraform.tfstate file, and it ran without the previous error. However, one of the resources will be destroyed, as shown below. Has the logic changed in the module.github.github_team_membership.alz module in version 4.3.3, and does it now mismatch the values in the [inputs-github.yaml](https://raw.githubusercontent.com/Azure/alz-terraform-accelerator/refs/heads/main/templates/platform_landing_zone/examples/bootstrap/inputs-github.yaml) file?

```
  # module.github.github_team_membership.alz["thomasxxx"] will be destroyed
  # (because key ["thomasxxxx"] is not in for_each map)
  - resource "github_team_membership" "alz" {
      - etag     = "W/\"xxxxx\"" -> null
      - id       = "xxx:thomasxxxx" -> null
      - role     = "member" -> null
      - team_id  = "xxxx" -> null
      - username = "thomasxxxx" -> null
    }
```

**Comment by jaredfholgate** [comment]
> Hi,
> 
> I edited the bootstrap v4.3.3 terraform.tfstate file, and it ran without the previous error. However, one of the resources will be destroyed, as shown below. Has the logic changed in the module.github.github_team_membership.alz module in version 4.3.3, and does it now mismatch the values in the [inputs-github.yaml](https://raw.githubusercontent.com/Azure/alz-terraform-accelerator/refs/heads/main/templates/platform_landing_zone/examples/bootstrap/inputs-github.yaml) file?
> 
> ```
>   # module.github.github_team_membership.alz["thomasxxx"] will be destroyed
>   # (because key ["thomasxxxx"] is not in for_each map)
>   - resource "github_team_membership" "alz" {
>       - etag     = "W/\"xxxxx\"" -> null
>       - id       = "xxx:thomasxxxx" -> null
>       - role     = "member" -> null
>       - team_id  = "xxxx" -> null
>       - username = "thomasxxxx" -> null
>     }
> ```

There haven't been any changes to this logic that I am aware of or can see in the history.
